In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.4 MB 5.9 MB/s 
     |████████████████████████████████| 6.6 MB 28.6 MB/s 
     |████████████████████████████████| 596 kB 35.3 MB/s 
     |████████████████████████████████| 101 kB 10.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
xtrain = torch.load('./drive/MyDrive/MLProject/xtrainconvnext.pt',map_location=torch.device('cpu'))
ytrain = torch.load('./drive/MyDrive/MLProject/ytrainconvnext.pt',map_location=torch.device('cpu'))
xtest = torch.load('./drive/MyDrive/MLProject/xtestconvnext.pt',map_location=torch.device('cpu'))
ytest = torch.load('./drive/MyDrive/MLProject/ytestconvnext.pt',map_location=torch.device('cpu'))

In [5]:
len(xtrain)

12500

In [6]:
xtrain[0].logits

tensor([[ 0.2807, -0.1915, -0.0483,  ...,  0.3331, -0.0385, -0.2025],
        [ 0.0661, -0.1783, -0.1671,  ...,  0.2006, -0.0202, -0.1991],
        [ 0.1508, -0.0920, -0.1021,  ..., -0.4148, -0.0653, -0.0228],
        [ 0.1879, -0.1742,  0.1941,  ...,  0.2381, -0.0053, -0.3509]])

In [7]:
xtest[0].logits

tensor([[-1.1199e-02, -5.6433e-02, -3.1322e-01, -1.3349e-01,  2.5049e-01,
         -1.2538e-01, -3.0859e-01,  1.7144e-01, -1.3632e-01, -2.3874e-01,
          8.8335e-03, -5.7182e-01, -4.8686e-01, -1.7605e-01, -7.2251e-02,
         -3.5781e-01, -4.3109e-01, -4.9361e-02, -3.9253e-01, -5.7819e-02,
          1.0218e-01,  2.6472e-01,  1.4917e-02, -2.3203e-01, -2.2553e-01,
          2.2213e-01, -4.3864e-01,  6.6252e-01, -2.5949e-01,  1.4875e-01,
         -6.8844e-02, -3.0505e-01,  9.9093e-02, -1.5189e-01,  1.9832e-01,
          2.7055e-02,  4.7800e-01, -6.6196e-03, -8.3111e-03,  5.3400e-01,
         -3.2988e-01,  2.3617e-01, -1.3836e-01,  4.0623e-01,  3.0254e-02,
          6.9628e-01, -3.7504e-01, -4.7689e-01,  1.5436e-01,  1.7066e-01,
         -5.6513e-01, -2.4083e-02, -2.6266e-01,  2.4451e-01, -1.8486e-01,
          5.5242e-02, -1.5995e-01, -3.9325e-01, -3.4938e-01, -7.8060e-02,
          1.8208e-01, -6.0878e-01, -7.3585e-01, -1.3590e-01,  1.7255e-01,
          8.6669e-02,  7.4937e-01,  5.

In [8]:
ytrain[0]

tensor([6, 5, 4, 6])

In [9]:
ytest[0]

tensor([3])

In [10]:
xtrain1 = []
for num, item in enumerate(xtrain):
  xtrain1.append(xtrain[num].logits)
xtest1 = []
for num, item in enumerate(xtest):
  xtest1.append(xtest[num].logits)

In [11]:
xtrain = xtrain1
xtest = xtest1

In [12]:
xtrain = torch.stack(xtrain)
xtrain.size()

torch.Size([12500, 4, 768])

In [13]:
ytrain = torch.stack(ytrain)
ytrain.size()

torch.Size([12500, 4])

In [14]:
xtest = torch.stack(xtest)
xtest.size()

torch.Size([10000, 1, 768])

In [15]:
ytest = torch.stack(ytest)
ytest.size()

torch.Size([10000, 1])

In [16]:
xtrain = xtrain.cpu()
xtrain = xtrain.numpy()
xtrain = xtrain.T.reshape(768,50000)

In [17]:
xtrain.shape

(768, 50000)

In [18]:
ytrain = ytrain.cpu()
ytrain = ytrain.numpy()
ytrain = ytrain.T.reshape(1,50000)

In [19]:
ytrain.shape

(1, 50000)

In [20]:
xtest = xtest.cpu()
xtest = xtest.numpy()
xtest = xtest.T.reshape(768,10000)

In [21]:
xtest.shape

(768, 10000)

In [22]:
ytest = ytest.cpu()
ytest = ytest.numpy()
ytest = ytest.T.reshape(1,10000)

In [23]:
ytest.shape

(1, 10000)

In [24]:
ytrain = ytrain.flatten()

In [25]:
xtrain = xtrain.T

In [26]:
xtrain.shape

(50000, 768)

In [27]:
ytrain.shape

(50000,)

In [28]:
xtest = xtest.T

In [29]:
ytest = ytest.flatten()

In [42]:
!pip install scikeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [109]:
from keras.models import Sequential
from keras.layers import Dense
from scikeras.wrappers import KerasClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# from keras.metrics import SparseCategoricalAccuracy 
# from keras import utils
import tensorflow as tf

In [110]:
# https://www.tensorflow.org/xla/tutorials/autoclustering_xla
# https://stackoverflow.com/questions/64689483/how-to-do-multiclass-classification-with-keras
ytrain = tf.keras.utils.to_categorical(ytrain, num_classes=10)

In [111]:
n_inputs = xtrain.shape[1]
def model():
  model = Sequential()
  model.add(Dense(100, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
  model.add(Dense(10, activation='softmax'))
  model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model


In [112]:
estimators = []
estimators.append(('mlp', KerasClassifier(model=model, epochs=20, batch_size=5, verbose=1)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=2)
results = cross_val_score(pipeline, xtrain, ytrain, cv=kfold)

Epoch 1/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.2900 - accuracy: 0.9065
Epoch 2/20
5000/5000 [==============================] - 15s 3ms/step - loss: 0.1871 - accuracy: 0.9376
Epoch 3/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.1358 - accuracy: 0.9525
Epoch 4/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0962 - accuracy: 0.9663
Epoch 5/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0709 - accuracy: 0.9755
Epoch 6/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0505 - accuracy: 0.9822
Epoch 7/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0368 - accuracy: 0.9869
Epoch 8/20
5000/5000 [==============================] - 17s 3ms/step - loss: 0.0292 - accuracy: 0.9897
Epoch 9/20
5000/5000 [==============================] - 14s 3ms/step - loss: 0.0239 - accuracy: 0.9920
Epoch 10/20
5000/5000 [==============================] - 13s 3ms/step - l

In [113]:
print("Result: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Result: 92.20% (0.10%)


In [114]:
from sklearn import metrics
from sklearn.model_selection import cross_val_predict
cross_val_predicted = cross_val_predict(pipeline, xtrain, ytrain, cv=2)
print(metrics.accuracy_score(ytrain, cross_val_predicted))
print(metrics.classification_report(ytrain, cross_val_predicted))

Epoch 1/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.2918 - accuracy: 0.9056
Epoch 2/20
5000/5000 [==============================] - 14s 3ms/step - loss: 0.1845 - accuracy: 0.9383
Epoch 3/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.1320 - accuracy: 0.9551
Epoch 4/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0947 - accuracy: 0.9668
Epoch 5/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0656 - accuracy: 0.9773
Epoch 6/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0485 - accuracy: 0.9830
Epoch 7/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0338 - accuracy: 0.9885
Epoch 8/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0292 - accuracy: 0.9891
Epoch 9/20
5000/5000 [==============================] - 12s 2ms/step - loss: 0.0220 - accuracy: 0.9921
Epoch 10/20
5000/5000 [==============================] - 11s 2ms/step - l

In [ ]:
print("Accuracy on Test set using NN: ",model.score(xtest,ytest))

In [ ]:
ypred = estimators[0].predict(xtest)

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
cm = confusion_matrix(ytest, ypred)
classes = ('Airplane', 'Car', 'Bird', 'Cat', 'Deer', 'Dog', 'Frog', 'Horse', 'Ship', 'Truck')
disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=classes)
# disp = ConfusionMatrixDisplay(confusion_matrix=cm)
# NOTE: Fill all variables here with default values of the plot_confusion_matrix
fig, ax = plt.subplots(figsize=(10, 10))
ax.set_xticklabels(classes)
disp = disp.plot(ax=ax,cmap='inferno')
plt.show()