In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached transformers-4.20.1-py3-none-any.whl (4.4 MB)
     |████████████████████████████████| 596 kB 4.9 MB/s 
     |████████████████████████████████| 6.6 MB 45.2 MB/s 
     |████████████████████████████████| 101 kB 1.7 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
xtrain = torch.load('./drive/MyDrive/MLProject/xtrainconvnext.pt',map_location=torch.device('cpu'))
ytrain = torch.load('./drive/MyDrive/MLProject/ytrainconvnext.pt',map_location=torch.device('cpu'))
xtest = torch.load('./drive/MyDrive/MLProject/xtestconvnext.pt',map_location=torch.device('cpu'))
ytest = torch.load('./drive/MyDrive/MLProject/ytestconvnext.pt',map_location=torch.device('cpu'))

In [ ]:
len(xtrain)

12500

In [ ]:
xtrain[0].logits

tensor([[-0.0970, -0.2797, -0.2374,  ...,  0.2035, -0.1968, -0.2819],
        [-0.0668,  0.4410, -0.7452,  ...,  0.0150, -0.2125,  0.2795],
        [ 0.2108, -0.0450, -0.7191,  ..., -0.2082, -0.2974,  0.1566],
        [-0.4496, -0.4706, -0.8118,  ..., -0.5422,  0.5650,  0.3224]])

In [ ]:
xtest[0].logits

tensor([[-1.9773e-01, -7.0178e-02, -3.7201e-01,  1.7608e-01,  1.9039e-01,
         -2.0810e-01, -7.4339e-02, -2.5052e-01,  1.5424e-01, -5.7588e-02,
          5.0018e-01, -1.6397e-02, -4.3196e-01, -5.2352e-02, -6.6966e-01,
          8.0492e-02, -1.0220e-01, -8.6355e-02, -7.3400e-01,  2.5742e-01,
          1.0769e-01, -5.2853e-01,  1.1252e-01, -1.2042e-01,  3.3263e-02,
          1.4191e-01,  1.5133e-01,  5.8903e-01, -1.4762e-01, -4.2799e-02,
         -9.6434e-02,  9.9700e-02,  2.9185e-01, -6.5392e-02, -1.5473e-01,
          8.7884e-02,  1.1074e-01, -2.7604e-01,  3.5598e-01, -1.7493e-01,
         -2.8661e-01,  6.7609e-02, -8.9845e-01,  7.2487e-01,  1.2117e-01,
          4.5008e-01, -7.8046e-02, -7.1369e-02,  4.3883e-01, -1.4440e-01,
         -1.7897e-01, -2.9359e-01, -1.8736e-01,  1.6721e+00, -1.1190e-01,
          2.4245e-01, -5.2655e-01, -6.1564e-01,  1.6131e-01, -1.4596e-01,
         -1.4417e-02, -2.5069e-01, -1.4239e-01,  2.2931e-01, -4.9707e-03,
          1.2725e-01, -3.2255e-01,  2.

In [ ]:
ytrain[0]

tensor([9, 3, 8, 2])

In [ ]:
ytest[0]

tensor([3])

In [ ]:
xtrain1 = []
for num, item in enumerate(xtrain):
  xtrain1.append(xtrain[num].logits)
xtest1 = []
for num, item in enumerate(xtest):
  xtest1.append(xtest[num].logits)

In [ ]:
xtrain = xtrain1
xtest = xtest1

In [ ]:
xtrain = torch.stack(xtrain)
xtrain.size()

torch.Size([12500, 4, 768])

In [ ]:
ytrain = torch.stack(ytrain)
ytrain.size()

torch.Size([12500, 4])

In [ ]:
xtest = torch.stack(xtest)
xtest.size()

torch.Size([10000, 1, 768])

In [ ]:
ytest = torch.stack(ytest)
ytest.size()

torch.Size([10000, 1])

In [ ]:
xtrain = xtrain.cpu()
xtrain = xtrain.numpy()
xtrain = xtrain.T.reshape(768,50000)

In [ ]:
xtrain.shape

(768, 50000)

In [ ]:
ytrain = ytrain.cpu()
ytrain = ytrain.numpy()
ytrain = ytrain.T.reshape(1,50000)

In [ ]:
ytrain.shape

(1, 50000)

In [ ]:
xtest = xtest.cpu()
xtest = xtest.numpy()
xtest = xtest.T.reshape(768,10000)

In [ ]:
xtest.shape

(768, 10000)

In [ ]:
ytest = ytest.cpu()
ytest = ytest.numpy()
ytest = ytest.T.reshape(1,10000)

In [ ]:
ytest.shape

(1, 10000)

In [ ]:
ytrain = ytrain.flatten()

In [ ]:
xtrain = xtrain.T

In [ ]:
xtrain.shape

(50000, 768)

In [ ]:
ytrain.shape

(50000,)

In [ ]:
xtest = xtest.T

In [ ]:
ytest = ytest.flatten()

In [ ]:
!pip install scikeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from scikeras.wrappers import KerasClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# from keras.metrics import SparseCategoricalAccuracy 
# from keras import utils
import tensorflow as tf

In [ ]:
# https://www.tensorflow.org/xla/tutorials/autoclustering_xla
# https://stackoverflow.com/questions/64689483/how-to-do-multiclass-classification-with-keras
ytrain = tf.keras.utils.to_categorical(ytrain, num_classes=10)

In [ ]:
n_inputs = xtrain.shape[1]
def model():
  model = Sequential()
  model.add(Dense(100, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
  model.add(Dense(10, activation='softmax'))
  model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model


In [ ]:
estimators = []
estimators.append(('mlp', KerasClassifier(model=model, epochs=20, batch_size=5, verbose=1)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=2)
results = cross_val_score(pipeline, xtrain, ytrain, cv=kfold)

Epoch 1/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0282 - accuracy: 0.9923
Epoch 2/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0081 - accuracy: 0.9978
Epoch 3/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0067 - accuracy: 0.9980
Epoch 4/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0054 - accuracy: 0.9986
Epoch 5/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0030 - accuracy: 0.9992
Epoch 6/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0026 - accuracy: 0.9994
Epoch 7/20
5000/5000 [==============================] - 10s 2ms/step - loss: 7.7156e-04 - accuracy: 0.9996
Epoch 8/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0011 - accuracy: 0.9998
Epoch 9/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0015 - accuracy: 0.9997
Epoch 10/20
5000/5000 [==============================] - 10s 2ms/step

In [ ]:
from sklearn import metrics
from sklearn.model_selection import cross_val_predict
cross_val_predicted = cross_val_predict(pipeline, xtrain, ytrain, cv=2)
print(metrics.accuracy_score(ytrain, cross_val_predicted))
print(metrics.classification_report(ytrain, cross_val_predicted))

Epoch 1/20
5000/5000 [==============================] - 11s 2ms/step - loss: 0.0295 - accuracy: 0.9926
Epoch 2/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0096 - accuracy: 0.9971
Epoch 3/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0075 - accuracy: 0.9982
Epoch 4/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0045 - accuracy: 0.9989
Epoch 5/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0028 - accuracy: 0.9995
Epoch 6/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0025 - accuracy: 0.9996
Epoch 7/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0022 - accuracy: 0.9994
Epoch 8/20
5000/5000 [==============================] - 10s 2ms/step - loss: 0.0018 - accuracy: 0.9994
Epoch 9/20
5000/5000 [==============================] - 10s 2ms/step - loss: 7.0117e-04 - accuracy: 0.9998
Epoch 10/20
5000/5000 [==============================] - 10s 2ms/step

In [ ]:
print("Result: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Result: 99.62% (0.07%)
